# Generated by Django 4.1.5 on 2023-02-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
