# Generated by Django 4.1.5 on 2023-04-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_get',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
