# Generated by Django 4.1.5 on 2023-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_publicmodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicmodel',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
